version: '3.8'

services:
  frontend-service:
    build: .
    container_name: frontend-service
    ports:
      - "4200:80"
    depends_on:
      - movie-service
      - review-service
    networks:
      - bookmyseat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  bookmyseat-network:
    driver: bridge