name: Deploy to AWS Amplify

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::543816070942:role/AWSAmplify_Angular_Role_AK
          aws-region: us-east-1

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

 # Check if the Amplify app 'bookmyseat' exists
      - name: Check if Amplify app exists
        id: amplify_check
        run: |
          # Get the list of Amplify apps and check if 'bookmyseat' is present
          amplify_apps=$(aws amplify list-apps --query "apps[?name=='bookmyseat'].name" --output text)
          
          if [[ "$amplify_apps" == "bookmyseat" ]]; then
            echo "Amplify app 'bookmyseat' exists. Skipping amplify init."
            echo "EXISTING_APP=true" >> $GITHUB_ENV
          else
            echo "Amplify app 'bookmyseat' does not exist. Proceeding with amplify init."
            echo "EXISTING_APP=false" >> $GITHUB_ENV
          fi

      # Initialize Amplify project if app doesn't exist
      - name: Initialize Amplify Project
        if: env.EXISTING_APP == 'false'
        run: |
          amplify init --yes

      # Fetch the existing Amplify project details if app exists
      - name: Pull Amplify project details
        if: env.EXISTING_APP == 'true'
        run: |
          amplify pull --appId YOUR_APP_ID --envName prod --yes

      
      # Install dependencies (Angular app)
      - name: Install dependencies
        run: npm install

      # Build Angular app
      - name: Build Angular app
        run: npx ng build frontend-service --configuration production
        env:
          API_BASE_URL_SEAT: ${{ secrets.API_BASE_URL_SEAT }}   # pass API URL via secrets/env variables
          API_BASE_URL_REVIEW: ${{ secrets.API_BASE_URL_REVIEW }}

      # Deploy the Angular app to Amplify
      - name: Deploy to Amplify
        run: amplify publish --yes
